[fonts]
roboto = RobotoMono Nerd Font:style=Regular:size=11
robotobold = RobotoMono Nerd Font:style=Bold:size=11
robotoitalic = RobotoMono Nerd Font:style=Italic:size=9

[colors]
; Nightfly Primary Colors
background = #011627
foreground = #bdc1c6
bright-foreground = #eeeeee

; Nightfly Normal Colors
black = #1d3b53
red = #fc514e
green = #a1cd5e
yellow = #e3d18a
blue = #82aaff
magenta = #c792ea
cyan = #7fdbca
white = #a1aab8

; Nightfly Bright Colors
bright-black = #7c8f8f
bright-red = #ff5874
bright-green = #21c7a8
bright-yellow = #ecc48d
bright-blue = #82aaff
bright-magenta = #ae81ff
bright-cyan = #7fdbca
bright-white = #d6deeb

; Functional Mappings for your modules
light-red = ${colors.bright-red}
light-green = ${colors.bright-green}
light-purple = ${colors.magenta}

menucol-yellow = ${colors.yellow}
menucol-blue = ${colors.blue}
menucol-orange = #ff966c 
menucol-red = ${colors.red}
menucol-green = ${colors.green}
menucol-sealine = ${colors.cyan}
menucol-purple = ${colors.magenta}
menucol-pink = ${colors.bright-magenta}
menucol-deepblue = #335880
menucol-lightblue = ${colors.bright-cyan}

fav-purple = ${colors.magenta}
dark = ${colors.background}
dark-red = #2d1a1a
dark-green = #1a2d23
dark-purple = #1d1a2d
light = ${colors.foreground}
gray = ${colors.bright-black}
dark-gray = ${colors.black}

[bar/main]
enable-ipc = true
override-redirect = false

bottom = false
width = 100%
height = 40

background = ${colors.background}
foreground = ${colors.foreground}

line-color = ${colors.blue}

line-size = 2

separator = "   "

;List of fonts
font-0 = ${fonts.roboto}
font-1 = ${fonts.robotobold}
font-2 = ${fonts.robotoitalic}

modules-left = workspaces brightness
modules-center = date layout 
modules-right = cpu temperature memory sound tray battery 


;Date correction
[module/date]
type = internal/date

time = %H:%M
date = %A, %B %d
date-alt = %A, %B %d, %Y
time-alt = %H:%M:%S

format-prefix = " "
format-padding = 2
format-underline = ${colors.blue}
format-foreground = ${colors.blue}
label-foreground = ${colors.foreground}
interval = 20

label = %date%, %time%
label-font = 2

;Workspaces
[module/workspaces]
type = internal/i3

pin-workspaces = true
strip-wsnumbers = true
index-sort = true

format = <label-state> <label-mode>

label-dimmed-underline = ${colors.background}

;On editing mode (resize for ex)
label-mode = %mode%
label-focused-background = ${colors.black}
label-focused-underline = ${colors.blue}
label-unfocused-foreground = ${colors.gray}
label-urgent-background = ${colors.dark-red}
label-urgent-underline = ${colors.red}
label-mode-padding = 2
label-mode-font = 3

label-focused = %index%
label-focused-padding = 3
label-focused-font = 3

label-unfocused = %index%
label-unfocused-padding = 3
label-unfocused-font = 3

label-visible = %index%
label-visible-background = ${colors.dark-purple}
label-visible-underline = ${colors.light-purple}
label-visible-padding = 3
label-visible-font = 3

label-urgent = %index%
;label-urgent-background = ${colors.dark-red}
;label-urgent-underline = ${colors.light-red}
label-urgent-padding = 3
label-urgent-font = 3

;Network
[module/wifi]
type = internal/network
interface = wlp3s0
format-connected =  <ramp-signal>
format-connected-padding = 2
format-connected-foreground = ${colors.menucol-green}
format-connected-underline = ${colors.menucol-green}

format-disconnected = " "
format-disconnected-font = 7
format-disconnected-padding = 2
format-disconnected-foreground = ${colors.menucol-yellow}
format-disconnected-underline = ${colors.menucol-yellow}

ramp-signal-0 = " "
ramp-signal-1 = "▂"
ramp-signal-2 = "▄"
ramp-signal-3 = "▅"
ramp-signal-4 = "▇"
ramp-signal-font = 7
ramp-signal-foreground = ${colors.light}


;Sound
[module/sound]
type = internal/pulseaudio

format-volume = <ramp-volume> <label-volume>
format-volume-padding = 2
format-volume-underline = ${colors.menucol-sealine}

label-volume = " %percentage%"
label-volume-font = 3

label-muted =  (%percentage%)
label-muted-font = 3
label-muted-padding = 2
label-muted-foreground = ${colors.gray}
label-muted-underline = ${colors.gray}

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-font = 7
ramp-volume-foreground = ${colors.menucol-sealine}

[module/brightness]
type = internal/backlight
card = intel_backlight
poll-interval = 0
use-actual-brightness = true
enable-scroll = true
scroll-interval = 10

; Available tags:
;   <label> (default)
;   <ramp>
;   <bar>
format = <label> <bar> 
label = " 󰃟 " 

; Only applies if <bar> is used
bar-width = 10
bar-indicator = |
bar-fill = ─
bar-empty = ─


;Keyboard Layout
[module/layout]
type = internal/xkeyboard
blacklist-0 = num lock
blacklist-1 = caps lock
blacklist-2 = scroll lock

;layout-icon-0 = us;EN
;layout-icon-1 = si;SI
;label-layout = %layout%
;label-layout-font = 2
;label-layout-foreground = ${colors.light}
;click-left = setxkbmap -layout us,si -option grp:win_space_toggle

; Available tags:
;   <label-layout> (default)
;   <label-indicator> (default)
format = <label-layout> <label-indicator>
format-spacing = 0
layout-icon = true

format-prefix = "  "
format-underline = ${colors.menucol-blue}
format-foreground = ${colors.menucol-blue}
format-padding = 2

; Available tokens:
;   %layout%
;   %name%
;   %number%
;   %icon%
;   %variant% (New in version 3.6.0)
; Default: %layout%
label-layout = %name%

click-left = xkeyboard

;Battery Indicator
[module/battery]
type = internal/battery
battery = BAT1
full-at = 100

; Available tags:
;   <label-charging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-charging>
format-charging = <animation-charging> <label-charging>
format-charging-underline = ${colors.menucol-orange}

; Available tags:
;   <label-discharging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-discharging>
format-discharging = <animation-discharging> <label-discharging>
format-discharging-underline = ${colors.menucol-orange}

; Available tags:
;   <label-full> (default)
;   <bar-capacity>
;   <ramp-capacity>
format-full = <label-full>
format-full-underline = ${colors.menucol-orange}

; Format used when battery level drops to low-at
; If not defined, format-discharging is used instead.
; Available tags:
;   <label-low>
;   <animation-low>
;   <bar-capacity>
;   <ramp-capacity>
; New in version 3.6.0
;format-low = <label-low> <animation-low>

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
;   %time%
;   %consumption% (shows current charge rate in watts)
label-charging = " %percentage%%"

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
;   %time%
;   %consumption% (shows current discharge rate in watts)
label-discharging = %percentage%%

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
label-full = "  %percentage%% "
label-full-foreground = ${colors.menucol-orange}

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
;   %time%
;   %consumption% (shows current discharge rate in watts)
; New in version 3.6.0
label-low = BATTERY LOW

; Only applies if <bar-capacity> is used
bar-capacity-width = 10

; Only applies if <animation-charging> is used
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
; Framerate in milliseconds
animation-charging-framerate = 750
animation-charging-foreground = ${colors.menucol-orange}

; Only applies if <animation-discharging> is used
animation-discharging-0 = 
animation-discharging-1 = 
animation-discharging-2 = 
animation-discharging-3 = 
animation-discharging-4 = 
; Framerate in milliseconds
animation-discharging-framerate = 500
animation-discharging-foreground = ${colors.menucol-orange}

[module/cpu]
type = internal/cpu
interval = 0.5
format = <label>
format-padding = 2
format-underline = ${colors.menucol-red}

format-prefix = 
format-prefix-foreground = ${colors.menucol-red}

label = " %percentage%"
label-font = 3

[module/memory]
type = internal/memory
interval = 3
format = <label>
format-padding = 2
format-underline = ${colors.menucol-purple}

format-prefix = 
format-prefix-foreground = ${colors.menucol-purple}

label = "  %gb_used% "
label-font = 3

[module/temperature]
type = internal/temperature
interval = 0.5
format = <ramp> <label>
format-padding = 2
format-underline = ${colors.menucol-deepblue}

format-warn = <ramp> <label-warn>
label = %temperature-c%
label-font = 3

label-warn = " %temperature-c% "
label-warn-font = 3

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-3 = 
ramp-4 = 
ramp-font = 7
ramp-foreground = ${colors.menucol-deepblue}

[module/tray]
type = internal/tray

format-underline = ${colors.menucol-yellow}
format-margin = 10px
tray-spacing = 20px
tray-size = 65%
